try:
    import face_recognition
    print("face_recognition imported successfully")

    import face_recognition_models
    print("face_recognition_models imported successfully")

except Exception as e:
    print("ERROR:", e)
